---
- hosts: "{{ host }}"
  vars:
    home: "{{ ansible_env.HOME }}"
    branch: master
    #branch: stable/juno
    devstack_dir: "{{ home }}/devstack"
    horizon_i18n_tools_dir: "{{ home }}/horizon-i18n-tools"
    enable_cron: no
  tasks:
  - name: Install git
    apt: pkg={{ item }} state=installed
    with_items:
      - git
    sudo: yes
  - name: git clone devstack
    git: repo=http://git.openstack.org/openstack-dev/devstack.git
         dest={{ devstack_dir }}
         version={{ branch }}
         force=no
  - name: git clone horizon-i18n-tools
    git: repo=https://github.com/amotoki/horizon-i18n-tools.git
         dest={{ horizon_i18n_tools_dir }}
         force=no
  - name: Install pip
    apt: pkg=python-pip state=installed
    sudo: yes
  - name: Install transifex client
    pip: name=transifex-client
    sudo: yes
  - name: Copy local.conf and 99-horizon-i18n
    template: src={{ item.src }} dest={{ item.dest }} backup=yes
    with_items:
    - src: templates/local.conf
      dest: "{{ devstack_dir }}/local.conf"
    - src: templates/99-horizon-i18n.sh
      dest: "{{ devstack_dir }}/extras.d/99-horizon-i18n.sh"
  - name: Install optional packages for OpenStack development
    apt: pkg={{ item }} state=installed
    with_items:
      - libmysqlclient-dev
      - libxml2-dev
      - libxslt1-dev
      - python-dev
      - libssl-dev
      - libffi-dev
    sudo: yes
  - name: cron import-trans.sh
    cron:
      name: "Horizon import trans"
      minute: 15
      job: "{{ horizon_i18n_tools_dir }}/import-trans.sh -r {{ branch|basename }}"
      user: "{{ ansible_env.USER }}"
    when: enable_cron|bool
  - name: disable cron import-trans.sh
    cron:
      name: "Horizon import trans"
      state: absent
    when: not enable_cron|bool
