- name: git clone horizon-i18n-tools
  git: repo=https://github.com/amotoki/horizon-i18n-tools.git
       dest={{ horizon_i18n_tools_dir }}
       version=master
       force=no

- name: Ensure /opt/stack
  file: state=directory
        path=/opt/stack
  sudo: yes

- name: Checkout openstack project-config repository
  git: repo=https://git.openstack.org/openstack-infra/project-config.git
       dest="/opt/stack/project-config"

- name: Ensure /usr/local/jenkins
  file: path=/usr/local/jenkins
        state=directory
  sudo: yes

- name: Symlink /usr/local/jenkins/slave_scripts
  file: src=/opt/stack/project-config/jenkins/scripts
        dest=/usr/local/jenkins/slave_scripts
        state=link
  sudo: yes
