# param: passwords: { name: value, ... }

- name: set password variable if non-default
  set_fact: "{{item.key}}={{item.value}}"
  when: item.value != "change_me"
  with_dict: passwords
  no_log: yes
